project/bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.index),
    path('<int:post_id>', views.bbs_detail, name='detail'),
    path('edit/<int:post_id>', views.post_edit_page),
    path('edit/action/', views.post_edit_page_action),
    path('like/<int:post_id>', views.like_post),
    path('comment/<int:post_id>/<int:comment_id>', views.post_comment_page, name='comment'),
    path('comment/action/', views.post_comment_page_action),
    path('delete/<int:comment_id>', views.delete_comment),
    path('delete_post/<int:post_id>', views.delete_post),
]

project/course/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'course'
urlpatterns = [
    url(r'^$', views.index),
    path('course/<str:course_cno>/', views.course_detail),
    path('teacher/<str:teacher_tno>/', views.teacher_detail),
    path('upload/', views.upload_file),
    path('upload/action/', views.upload_file_action),
    path('download/<int:file_id>', views.download_file),
    path('like_file/<int:file_id>', views.like_file),
    path('delete_file/<int:file_id>', views.delete_file),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.urls import re_path
from django.conf import settings
from django.views.static import serve
from login import views

urlpatterns = [
    url(r'^$', views.login),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('captcha/', include('captcha.urls')),
    path('about/', views.about),
    path('course/', include('course.urls')),
    path('bbs/', include('bbs.urls')),
    path('editnickname/', views.editnickname),
    path('editemail/', views.editemail),
    path('editpwd/', views.editpwd),
    path('editphoto/', views.editphoto),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^search/', include('haystack.urls')),
    path('info/<int:sno>', views.info, name='info'),
    path('likes/', views.likes),
    path('posts/', views.posts),
    path('comments/', views.comments),
    path('send/<int:sno>', views.send),
    path('mailbox/', views.mailbox),
    path('follow/<int:sno>', views.follow),
    path('follows/', views.follows),
    path('follow_cancel/<int:sno>', views.follow_cancel),
    path('posts/<int:sno>', views.posts_ta),
]

project/course/models.py
from django.db import models
from login.models import User


def file_directory_path(instance, filename):
    ext = filename.split('.').pop()
    filename = '{0}{1}.{2}'.format(instance.title, instance.course.cno, ext)
    return filename


class Course(models.Model):
    cno = models.CharField(max_length=128, unique=True, primary_key=True)  # 课号
    name = models.CharField(max_length=128)  # 课程名
    credit = models.IntegerField(default=0)  # 学分
    outline = models.CharField(max_length=2048, default='略')  # 授课大纲
    references = models.CharField(max_length=1024, default='略')  # 教材与参考资料
    mean_score = models.FloatField(default=0)  # 平均分
    fail_rate = models.FloatField(default=0)  # 挂科率

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-cno"]
        verbose_name = "课程"
        verbose_name_plural = "课程"


class Teacher(models.Model):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    school = (
        ('chuan_jian', "船舶海洋与建筑工程学院"),
        ('ji_dong', "机械动力与工程学院"),
        ('dian_yuan', "电子信息与电气工程学院"),
        ('cai_liao', "材料科学与工程学院"),
        ('shu_xue', "数学科学学院"),
        ('wu_li', "物理与天文学院"),
        ('hua_xue', "化学化工学院"),
        ('sheng_ming', "生命科学技术学院"),
        ('sheng_yi_gong', "生物医学工程学院"),
        ('an_tai', "安泰经济与管理学院"),
        ('qi_ta', "其它"),  # 暂时写到这儿
    )

    tno = models.CharField(max_length=128, unique=True, primary_key=True)  # 职工号
    name = models.CharField(max_length=128)  # 名字
    title = models.CharField(max_length=128)  # 职称
    email = models.EmailField(unique=True)  # 邮箱
    sex = models.CharField(max_length=32, choices=gender)  # 性别（选择）
    institute = models.CharField(max_length=256, choices=school)  # 学院（选择）
    department = models.CharField(max_length=256, default='--')  # 系（暂时为填写）
    address = models.CharField(max_length=256, default='--')  # 办公室地点
    resume = models.CharField(max_length=2048, default='略')  # 简历
    course = models.ManyToManyField(Course, verbose_name='课程')  # 教授课程

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-tno"]
        verbose_name = "教师"
        verbose_name_plural = "教师"


class File(models.Model):
    title = models.CharField(max_length=128)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    introduction = models.CharField(max_length=256, null=True)
    likes = models.IntegerField(default=0)
    like_users = models.ManyToManyField(User, verbose_name='用户', related_name='like_users_file')
    downloads = models.IntegerField(default=0)
    create_time = models.DateTimeField('上传时间', auto_now_add=True)
    file = models.FileField(upload_to=file_directory_path)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-create_time"]
        verbose_name = "文件"
        verbose_name_plural = "文件"

project/course/forms.py
from django import forms
from . import models

COURSE = models.Course.objects.all()

class UploadForm(forms.Form):
    title = forms.CharField(label="题目", required=True, max_length=50)
    course = forms.ModelChoiceField(label="课程", queryset=COURSE, empty_label='请选择课程')
    introduction = forms.CharField(label="简介", widget=forms.Textarea(), max_length=256)
    file = forms.FileField(label="文件")

project/course/views.py
from django.shortcuts import render, redirect
from django.http import FileResponse
from django.utils.encoding import escape_uri_path
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, InvalidPage
from .models import Course, Teacher, File
from .forms import UploadForm
from login.models import User


def index(request):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    user = User.objects.get(sno=request.session['user_sno'])
    course_list = Course.objects.order_by('cno')
    teacher_list = Teacher.objects.order_by("tno")
    file_set = File.objects.order_by("-create_time")

    pag_file = Paginator(file_set, 8)
    if request.method == "GET":
        page = request.GET.get('page')
        try:
            file_list = pag_file.page(page)
        except PageNotAnInteger:
            file_list = pag_file.page(1)
        except InvalidPage:
            return HttpResponse('找不到页面的内容')
        except EmptyPage:
            file_list = pag_file.page(pag_file.num_pages)
    else:
        file_list = pag_file.page(1)

    ctx = {'user': user, 'course_list': course_list, 'teacher_list': teacher_list, 'file_list': file_list}
    return render(request, 'index.html', ctx)


def course_detail(request, course_cno):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    course = Course.objects.get(pk=course_cno)
    ctx = {
        'course': course,
        'teachers': course.teacher_set.all()
    }
    return render(request, 'courses/detail.html', ctx)


def teacher_detail(request, teacher_tno):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    teacher = Teacher.objects.get(pk=teacher_tno)
    ctx = {
        'teacher': teacher,
        'courses': teacher.course.all()
    }
    return render(request, 'teachers/detail.html', ctx)


def upload_file(request):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    upload_form = UploadForm()
    message = ""
    return render(request, 'upload_file.html', locals())


def upload_file_action(request):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    if request.method == 'POST':
        upload_form = UploadForm(request.POST, request.FILES)
        if upload_form.is_valid():
            title = upload_form.cleaned_data.get('title')
            course = upload_form.cleaned_data.get('course')
            introduction = upload_form.cleaned_data.get('introduction')
            file = upload_form.cleaned_data.get('file')
            user = User.objects.get(sno=request.session['user_sno'])
            File.objects.create(title=title, course=course, user=user, introduction=introduction, file=file)
            return redirect(r"/course/")
    message = '文件上传失败！'
    return render(request, 'upload_file.html', {'message': message})


def download_file(request, file_id):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    file = File.objects.get(id=file_id)
    file.downloads += 1
    file.save()
    response =FileResponse(open('./upload/'+str(file.file),'rb') )
    response['Content-Type']='application/octet-stream'
    response['Content-Disposition']='attachment;filename="{0}"'.format(escape_uri_path(str(file.file)))
    return response


def like_file(request, file_id):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    file = File.objects.get(id=file_id)
    user = User.objects.get(sno=request.session['user_sno'])
    if user not in file.like_users.all():
        file.likes += 1
        file.like_users.add(user)
        file.save()
    return redirect("/course/")


def delete_file(request, file_id):
    if not request.session.get('is_login', None):
        return redirect("/login/login/")
    file = File.objects.get(id=file_id)
    file.delete()
    return redirect("/course/")

project/course/templates/teachers/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <meta charset="UTF-8">
  <title>教师详情</title>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">交大知乎</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class=""><a href="/login/index/">主页<span class="sr-only">(current)</span></a></li>
          <li><a href="/course/">课程</a></li>
          <li><a href="/bbs/">社区</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="/about/">{{ request.session.user_name }}</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">我的<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/likes/">我的点赞</a></li>
              <li><a href="/posts/">我的发布</a></li>
              <li><a href="/comments/">我的评论</a></li>
              <li><a href="/mailbox/">我的信箱</a></li>
              <li><a href="/follows/">我的好友</a></li>
            </ul>
          </li>
          <li><a href="/login/logout/">登出</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!--基础导航栏-->

  <br /><br /><br /><br />
  <div class="text-center">
    <h1>教师详细信息</h1>
  </div>
  <br /><br />
  <!--标题-->

  <div class="row container-fluid">
    <div class="col-xs-3"></div>
    <div class="col-xs-6 table-responsive">
      <table class="table table-bordered">
        <tbody class="text-center">
          <tr>
            <td><b>姓名</b></td>
            <td>{{ teacher.name }}</td>
          </tr>
          <tr>
            <td><b>工号</b></td>
            <td>{{ teacher.tno }}</td>
          </tr>
          <tr>
            <td><b>性别</b></td>
            <td>{{ teacher.get_sex_display }}</td>
          </tr>
          <tr>
            <td><b>职称</b></td>
            <td>{{ teacher.title }}</td>
          </tr>
          <tr>
            <td><b>学院</b></td>
            <td>{{ teacher.get_institute_display }}</td>
          </tr>
          <tr>
            <td><b>专业系</b></td>
            <td>{{ teacher.department }}</td>
          </tr>
          <tr>
            <td><b>邮箱</b></td>
            <td>{{ teacher.email }}</td>
          </tr>
          <tr>
            <td><b>办公地址</b></td>
            <td>{{ teacher.address }}</td>
          </tr>
          <tr>
            <td><b>简历</b></td>
            <td>{{ teacher.resume }}</td>
          </tr>
          <tr>
            <td><b>讲授课程</b></td>
            <td>
              {% for course in courses %}
              <li><a href="/course/course/{{ course.cno }}/"> {{ course.name }}</a></li>
              {% endfor %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-xs-2"></div>
  </div>
</body>

</html>

project/course/templates/teachers/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>教师主页</title>
</head>

<body>
  <h1>教师主页</h1>
  <a href="/course/">返回课程信息页</a>
  {% if teacher_list %}
  <ul>
    {% for teacher in teacher_list %}
    <li><a href="/course/teacher/{{ teacher.tno }}/">{{ teacher.name }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No teachers are available.</p>
  {% endif %}
</body>

</html>